name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        
    steps:
    - uses: actions/checkout@v4
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
    - name: Install dependencies
      run: |
        pdm sync --no-editable
    - name: Run static code analysis
      run: |
        pdm lint
    - name: Run Tests
      run: |
        pdm test --junit-xml=test-results.xml --cov-report xml:coverage.xml
    - name: Publish tests result
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: test-results.xml
        summary: true
        fail-on-empty: true
        # (Optional) Title of the test results section in the workflow summary
        title: Tests result - ${{ matrix.python-version }}
    - name: Publish code coverage
      if: always()
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: coverage.xml
        junitxml-path: test-results.xml
